name: Staging Pipeline

on:
  push:
    branches:
      - 'main'

jobs:
  deploy_staging:
    name: Deploy Staging
    runs-on: ubuntu-latest
    environment:
      name: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '21.1.0'

      - name: Install dependencies
        run: npm install

      - name: Lint and build code, then publish to Netlify
        run: netlify deploy --prod --dir=.next --build "npm run build"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}

      - name: Success
        run: echo "🛠️ Deploy successful 🛠️"
