name: Staging Pipeline

on:
  push:
    branches:
      - 'main'

jobs:
  deploy_staging:
    name: Deploy Staging
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '21.x'

      - name: Install dependencies
        run: npm install
        continue-on-error: false

      - name: Install Vercel CLI
        run: npm install -g vercel
        continue-on-error: false

      - name: Deploy to Vercel (Staging)
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN_STAGING }}
        env:
          VERCEL_TOKEN_STAGING: ${{ secrets.VERCEL_TOKEN_STAGING }}
        continue-on-error: false

      - name: Success
        run: echo "Deploy successful"
